/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BeautifulPdfPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/export.ts
var import_obsidian2 = require("obsidian");

// src/frame.ts
var DEFAULT_BG = {
  blockquote: "rgba(0,0,0,0.03)",
  callout: "#f5f8fb",
  embed: "#fafafa"
};
var DEFAULT_ACCENT = {
  blockquote: "#6b7280",
  callout: "#6b8cae",
  embed: "#bbbbbb"
};
function accentFor(kind, style) {
  if (kind === "blockquote")
    return style.color || DEFAULT_ACCENT.blockquote;
  return DEFAULT_ACCENT[kind];
}
function frameStyleExtras(kind, style) {
  var _a, _b;
  const preset = (_a = style.framePreset) != null ? _a : "accent-bar";
  const bg = (_b = style.backgroundColor) != null ? _b : DEFAULT_BG[kind];
  const accent = accentFor(kind, style);
  if (preset === "outline-card") {
    return [
      `background: ${bg}`,
      `border: 1px solid ${accent}`,
      "border-radius: 6px",
      "padding: 8pt 10pt"
    ];
  }
  if (preset === "soft-fill") {
    return [
      `background: ${bg}`,
      "border: none",
      "border-left: none",
      "border-radius: 0",
      "padding: 8pt 12pt"
    ];
  }
  const barWidth = kind === "callout" ? "4px" : kind === "embed" ? "2px" : "3px";
  return [
    `background: ${bg}`,
    `border: none`,
    `border-left: ${barWidth} solid ${accent}`,
    "border-radius: 4px",
    "padding: 6pt 10pt"
  ];
}
function applyFramePreview(sample, kind, style) {
  var _a, _b;
  const preset = (_a = style.framePreset) != null ? _a : "accent-bar";
  const bg = (_b = style.backgroundColor) != null ? _b : DEFAULT_BG[kind];
  const accent = accentFor(kind, style);
  sample.removeClass(
    "is-frame-accent-bar",
    "is-frame-outline-card",
    "is-frame-soft-fill",
    "is-frame-callout",
    "is-frame-embed",
    "is-frame-blockquote"
  );
  sample.addClass(`is-frame-${preset}`);
  sample.addClass(`is-frame-${kind}`);
  sample.setCssStyles({
    background: bg,
    borderColor: accent
  });
  if (preset === "accent-bar") {
    sample.setCssProps({
      "--bpf-frame-accent": accent
    });
  }
}

// src/util.ts
function toLineHeightPercent(value, fallback = 170) {
  if (value == null || Number.isNaN(value))
    return fallback;
  if (value > 0 && value <= 10)
    return Math.round(value * 100);
  return value;
}
function lineHeightCss(value, fallback = 170) {
  return `${toLineHeightPercent(value, fallback)}%`;
}
function applyPageBreakMarkers(markdown) {
  return markdown.replace(/%%\s*pdf-pagebreak\s*%%/gi, PAGE_BREAK_HTML).replace(/<!--\s*pdf-pagebreak\s*-->/gi, PAGE_BREAK_HTML).replace(/\\pagebreak\b/gi, PAGE_BREAK_HTML);
}
var PAGE_BREAK_HTML = '\n\n<div class="pdf-pagebreak" data-pdf-pagebreak="true"></div>\n\n';
var PAGE_BREAK_SNIPPET = "%%pdf-pagebreak%%\n";

// src/css.ts
function rule(selector, style, extra = []) {
  const decls = [
    `font-family: ${style.fontFamily}`,
    `font-size: ${style.fontSize}pt`,
    `font-weight: ${style.fontWeight}`,
    `text-align: ${style.align}`,
    `color: ${style.color}`,
    `margin-top: ${style.marginTop}pt`,
    `margin-bottom: ${style.marginBottom}pt`
  ];
  if (style.backgroundColor) {
    decls.push(`background: ${style.backgroundColor}`);
    decls.push(`background-color: ${style.backgroundColor}`);
  }
  if (style.lineHeight != null) {
    decls.push(`line-height: ${lineHeightCss(style.lineHeight)}`);
  }
  if (style.paddingLeft != null) {
    decls.push(`padding-left: ${style.paddingLeft}pt`);
  }
  decls.push(...extra);
  return `${selector} {
  ${decls.join(";\n  ")};
}`;
}
function profileToCss(profile) {
  var _a, _b, _c;
  const e = profile.elements;
  const p = profile.page;
  const parts = [];
  parts.push(`
*, *::before, *::after { box-sizing: border-box; }
html, body {
  margin: 0;
  padding: 0;
  background: #fff;
  color: ${e.body.color};
  font-family: ${e.body.fontFamily};
  font-size: ${e.body.fontSize}pt;
  line-height: ${lineHeightCss(p.lineHeight)};
  -webkit-print-color-adjust: exact;
  print-color-adjust: exact;
}
.markdown-preview-view,
.markdown-rendered {
  padding: 0 !important;
  margin: 0 !important;
  background: transparent !important;
  color: inherit;
  font-family: inherit;
  font-size: inherit;
  line-height: inherit;
  max-width: none !important;
}
.markdown-preview-view .mod-header,
.markdown-preview-sizer { max-width: none !important; width: 100% !important; margin: 0 !important; }
p { ${inline(e.body)} }
`);
  parts.push(rule("h1, h1.__title__", e.h1));
  parts.push(rule("h2", e.h2));
  parts.push(rule("h3", e.h3));
  parts.push(rule("h4", e.h4));
  parts.push(rule("h5", e.h5));
  parts.push(rule("h6", e.h6));
  parts.push(rule("blockquote", e.blockquote, frameStyleExtras("blockquote", e.blockquote)));
  parts.push(rule("ul, ol", e.list, ["padding-left: 1.4em"]));
  parts.push(rule("li", e.list, [
    `margin-top: 0`,
    `margin-bottom: ${Math.max(2, e.list.marginBottom / 2)}pt`
  ]));
  parts.push(rule("ul.contains-task-list, .task-list-item", e.taskList, [
    "list-style: none",
    "padding-left: 0"
  ]));
  parts.push(`
.task-list-item-checkbox,
input[type="checkbox"] {
  -webkit-appearance: none;
  appearance: none;
  width: 11pt;
  height: 11pt;
  margin: 0 0.45em 0 0;
  vertical-align: -1pt;
  border: 1px solid #555;
  border-radius: 2px;
  background: #fff !important;
  background-color: #fff !important;
  box-shadow: none !important;
  accent-color: #333;
}
.task-list-item-checkbox:checked,
input[type="checkbox"]:checked {
  background-color: #fff !important;
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath fill='none' stroke='%23333333' stroke-width='2' d='M3 8l3.5 3.5L13 4'/%3E%3C/svg%3E") !important;
  background-size: 90% 90% !important;
  background-position: center !important;
  background-repeat: no-repeat !important;
  border-color: #555;
}
`);
  parts.push(rule("code", e.codeInline, [
    `background: ${(_a = e.codeInline.backgroundColor) != null ? _a : "rgba(0,0,0,0.06)"}`,
    "padding: 0.1em 0.35em",
    "border-radius: 3px",
    "margin: 0"
  ]));
  parts.push(rule("pre, pre > code", e.codeBlock, [
    `background: ${(_b = e.codeBlock.backgroundColor) != null ? _b : "#f4f4f4"}`,
    "padding: 10pt",
    "border-radius: 4px",
    "overflow-x: auto",
    "white-space: pre-wrap",
    "word-break: break-word",
    "display: block",
    "position: relative"
  ]));
  parts.push(`pre code { background: transparent !important; padding: 0; }`);
  parts.push(`
.copy-code-button,
.code-block-buttons,
button.copy-code-button,
.markdown-rendered button.copy-code-button,
pre > button,
.edit-block-button {
  display: none !important;
  visibility: hidden !important;
  opacity: 0 !important;
  pointer-events: none !important;
}
`);
  parts.push(rule("hr", e.hr, [
    "border: none",
    `border-top: 1px solid ${e.hr.color}`,
    "height: 0"
  ]));
  parts.push(`
table {
  width: 100%;
  border-collapse: collapse;
  margin-top: ${e.table.marginTop}pt;
  margin-bottom: ${e.table.marginBottom}pt;
  font-family: ${e.table.fontFamily};
  font-size: ${e.table.fontSize}pt;
  color: ${e.table.color};
  line-height: ${lineHeightCss(e.table.lineHeight, 140)};
  break-inside: auto;
}
th, td {
  border: 1px solid #bbb;
  padding: 5pt 7pt;
  text-align: left;
  vertical-align: top;
}
th {
  font-family: ${e.tableHeader.fontFamily};
  font-size: ${e.tableHeader.fontSize}pt;
  font-weight: ${e.tableHeader.fontWeight};
  color: ${e.tableHeader.color};
  background: ${(_c = e.tableHeader.backgroundColor) != null ? _c : "#f0f0f0"};
}
tr { break-inside: avoid; }
`);
  parts.push(rule(".callout", e.callout, frameStyleExtras("callout", e.callout)));
  parts.push(rule(".callout-title", e.calloutTitle));
  parts.push(`.callout-content { margin-top: 4pt; }`);
  parts.push(`
img {
  max-width: 100%;
  height: auto;
  display: block;
  margin-top: ${e.image.marginTop}pt;
  margin-bottom: ${e.image.marginBottom}pt;
  margin-left: ${e.image.align === "center" ? "auto" : e.image.align === "right" ? "auto" : "0"};
  margin-right: ${e.image.align === "center" ? "auto" : "0"};
}
`);
  parts.push(rule("a", e.link, [
    "text-decoration: underline",
    "margin: 0"
  ]));
  parts.push(`a.internal-link { color: ${e.link.color}; }`);
  parts.push(rule(".footnote-ref, sup", e.footnote, [
    "margin: 0",
    "font-size: 0.75em"
  ]));
  parts.push(rule("section.footnotes, .footnotes", e.footnote, [
    "border-top: 1px solid #ccc",
    "padding-top: 8pt",
    "margin-top: 16pt"
  ]));
  parts.push(
    rule(
      // Note embeds only — image/media embeds must not get quote-like chrome
      ".internal-embed:not(.media-embed):not(.image-embed), .markdown-embed:not(.image-embed), .markdown-embed-content",
      e.embed,
      frameStyleExtras("embed", e.embed)
    )
  );
  parts.push(`
.internal-embed.media-embed,
.internal-embed.image-embed,
span.image-embed,
span.media-embed {
  background: transparent !important;
  border: none !important;
  border-left: none !important;
  padding: 0 !important;
  margin: 0 !important;
  border-radius: 0 !important;
  display: contents;
}
.internal-embed.media-embed img,
.internal-embed.image-embed img,
span.image-embed img {
  display: block;
}
`);
  parts.push(`
.frontmatter, .metadata-container, .mod-header .inline-title { display: none !important; }
.collapse-indicator, .clickable-icon { display: none !important; }
.copy-code-button, .code-block-buttons, .edit-block-button { display: none !important; }

.pdf-pagebreak {
  break-after: page;
  page-break-after: always;
  height: 0 !important;
  margin: 0 !important;
  padding: 0 !important;
  border: none !important;
  display: block;
}
`);
  return parts.join("\n");
}
function inline(style) {
  const decls = [
    `font-family: ${style.fontFamily}`,
    `font-size: ${style.fontSize}pt`,
    `font-weight: ${style.fontWeight}`,
    `text-align: ${style.align}`,
    `color: ${style.color}`,
    `margin-top: ${style.marginTop}pt`,
    `margin-bottom: ${style.marginBottom}pt`
  ];
  if (style.lineHeight != null)
    decls.push(`line-height: ${lineHeightCss(style.lineHeight)}`);
  return decls.join("; ") + ";";
}
function headerFooterTemplates(profile) {
  var _a, _b, _c, _d;
  const p = profile.page;
  const showHeader = Boolean((_a = p.headerText) == null ? void 0 : _a.trim()) || p.pageNumber.startsWith("top");
  const showFooter = Boolean((_b = p.footerText) == null ? void 0 : _b.trim()) || p.pageNumber.startsWith("bottom") || p.pageNumber !== "none";
  const pageSpan = (format) => {
    const html = format.replace(/\{page\}/g, `<span class="pageNumber"></span>`).replace(/\{pages\}/g, `<span class="totalPages"></span>`);
    return html;
  };
  const baseStyle = "font-size: 9px; font-family: sans-serif; color: #666; width: 100%; padding: 0 8mm; box-sizing: border-box;";
  let headerTemplate = "<span></span>";
  let footerTemplate = "<span></span>";
  if (p.pageNumber === "top-center" || p.headerText) {
    const num = p.pageNumber === "top-center" ? `<div style="text-align:center">${pageSpan(p.pageNumberFormat)}</div>` : "";
    const text = p.headerText ? `<div style="text-align:${(_c = p.headerAlign) != null ? _c : "left"}">${escapeHtml(p.headerText)}</div>` : "";
    headerTemplate = `<div style="${baseStyle}">${text}${num}</div>`;
  }
  if (p.pageNumber.startsWith("bottom") || p.footerText) {
    const numAlign = p.pageNumber === "bottom-right" ? "right" : p.pageNumber === "bottom-center" ? "center" : "left";
    const num = p.pageNumber !== "none" && p.pageNumber.startsWith("bottom") ? `<div style="text-align:${numAlign}">${pageSpan(p.pageNumberFormat)}</div>` : "";
    const text = p.footerText ? `<div style="text-align:${(_d = p.footerAlign) != null ? _d : "center"}">${escapeHtml(p.footerText)}</div>` : "";
    footerTemplate = `<div style="${baseStyle}">${text}${num}</div>`;
  }
  if (p.pageNumber === "none" && !p.headerText && !p.footerText) {
    return {
      displayHeaderFooter: false,
      headerTemplate: " ",
      footerTemplate: " "
    };
  }
  return {
    displayHeaderFooter: showHeader || showFooter,
    headerTemplate,
    footerTemplate
  };
}
function escapeHtml(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

// src/render.ts
var import_obsidian = require("obsidian");
async function renderNoteHtml(app, file, profile) {
  var _a, _b;
  const raw = await app.vault.cachedRead(file);
  const markdown = applyPageBreakMarkers(raw);
  const title = profile.page.useFilenameAsTitle ? file.basename : ((_b = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter) == null ? void 0 : _b.title) || file.basename;
  const comp = new import_obsidian.Component();
  comp.load();
  const host = document.body.createDiv({
    cls: "beautiful-pdf-render-host",
    attr: { style: "position:fixed;left:-10000px;top:0;width:800px;visibility:hidden;" }
  });
  const viewEl = host.createDiv({
    cls: "markdown-preview-view markdown-rendered"
  });
  if (profile.page.useFilenameAsTitle) {
    viewEl.createEl("h1", { text: title, cls: "__title__" });
  }
  try {
    await import_obsidian.MarkdownRenderer.render(app, markdown, viewEl, file.path, comp);
    await waitForEmbeds(viewEl);
    convertCanvases(viewEl);
    rewriteInternalImages(app, file, viewEl);
    cleanupImageEmbeds(viewEl);
    stripUiChrome(viewEl);
    const css = profileToCss(profile);
    const bodyHtml = viewEl.innerHTML;
    const htmlDocument = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>${escapeAttr(title)}</title>
<style>${css}</style>
</head>
<body>
<div class="markdown-preview-view markdown-rendered">
${bodyHtml}
</div>
</body>
</html>`;
    return { htmlDocument, title, bodyHtml, css };
  } finally {
    comp.unload();
    host.remove();
  }
}
async function waitForEmbeds(el2, ms = 800) {
  const hasHeavy = el2.querySelector("img, .internal-embed, .markdown-embed, canvas") != null;
  if (!hasHeavy)
    return;
  await sleep(ms);
}
function sleep(ms) {
  return new Promise((r) => window.setTimeout(r, ms));
}
function convertCanvases(el2) {
  el2.querySelectorAll("canvas").forEach((canvas) => {
    try {
      const img = createEl("img");
      img.src = canvas.toDataURL();
      img.alt = "canvas";
      canvas.replaceWith(img);
    } catch (e) {
    }
  });
}
function rewriteInternalImages(app, file, el2) {
  el2.querySelectorAll("img").forEach((img) => {
    const src = img.getAttribute("src");
    if (!src || src.startsWith("data:") || src.startsWith("http"))
      return;
    try {
      const dest = app.metadataCache.getFirstLinkpathDest(
        decodeURIComponent(src.split("?")[0]),
        file.path
      );
      if (dest) {
        const resPath = app.vault.adapter.getResourcePath(dest.path);
        img.setAttribute("src", resPath);
      }
    } catch (e) {
    }
  });
}
function cleanupImageEmbeds(el2) {
  const embeds = el2.querySelectorAll(
    ".internal-embed.media-embed, .internal-embed.image-embed, span.image-embed, span.media-embed"
  );
  embeds.forEach((span) => {
    const img = span.querySelector("img");
    if (!img) {
      span.remove();
      return;
    }
    Array.from(span.childNodes).forEach((node) => {
      var _a;
      if (node.nodeType === Node.TEXT_NODE)
        node.remove();
      else if (node !== img && node.tagName !== "IMG") {
        const nestedImg = (_a = node.querySelector) == null ? void 0 : _a.call(node, "img");
        if (!nestedImg)
          node.remove();
      }
    });
    const alt = img.getAttribute("alt") || "";
    if (alt.startsWith("[") || alt.includes("![[")) {
      img.setAttribute("alt", alt.replace(/^\[+|!?\[\[|\]\]$/g, "").trim());
    }
    span.replaceWith(img);
  });
  el2.querySelectorAll("p, div, span").forEach((block) => {
    Array.from(block.childNodes).forEach((node) => {
      if (node.nodeType !== Node.TEXT_NODE)
        return;
      const t = (node.textContent || "").trim();
      if (t === "[" || t === "]" || t === "![" || t === "[[") {
        node.remove();
      }
    });
  });
}
function stripUiChrome(el2) {
  el2.querySelectorAll(
    ".copy-code-button, .code-block-buttons, .edit-block-button, button.copy-code-button"
  ).forEach((node) => node.remove());
}
function escapeAttr(s) {
  return s.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;");
}

// src/export.ts
function getNodeRequire() {
  const win = window;
  if (typeof win.require !== "function") {
    throw new Error(
      "Electron remote API is unavailable. Beautiful PDF works on Obsidian desktop only."
    );
  }
  return win.require;
}
function getElectron() {
  const req = getNodeRequire();
  const electron = req("electron");
  const fs = req("fs");
  let remote = electron.remote;
  if (!remote) {
    try {
      remote = req("@electron/remote");
    } catch (e) {
    }
  }
  if (!(remote == null ? void 0 : remote.dialog)) {
    throw new Error(
      "Electron remote API is unavailable. Beautiful PDF works on Obsidian desktop only."
    );
  }
  return { remote, fs };
}
async function generatePdf(app, file, profile) {
  const rendered = await renderNoteHtml(app, file, profile);
  const data = await printHtmlToPdf(rendered, profile);
  return { data, title: rendered.title };
}
async function exportPdfToFile(app, file, profile, openAfter = true) {
  const notice = new import_obsidian2.Notice("Beautiful PDF: generating\u2026", 0);
  try {
    const { data, title } = await generatePdf(app, file, profile);
    const { remote, fs } = getElectron();
    const result = await remote.dialog.showSaveDialog({
      title: "Export Beautiful PDF",
      defaultPath: `${title}.pdf`,
      filters: [{ name: "PDF", extensions: ["pdf"] }],
      properties: ["showOverwriteConfirmation", "createDirectory"]
    });
    if (result.canceled || !result.filePath) {
      notice.hide();
      return null;
    }
    await fs.promises.writeFile(result.filePath, data);
    notice.hide();
    new import_obsidian2.Notice("Beautiful PDF: saved");
    if (openAfter) {
      await remote.shell.openPath(result.filePath);
    }
    return result.filePath;
  } catch (err) {
    notice.hide();
    console.error(err);
    new import_obsidian2.Notice(`Beautiful PDF error: ${String(err)}`);
    return null;
  }
}
async function printHtmlToPdf(rendered, profile) {
  const webview = createHiddenWebview();
  document.body.appendChild(webview);
  try {
    await waitForDomReady(webview);
    await webview.executeJavaScript(`
			(() => {
				document.head.innerHTML = "";
				document.body.innerHTML = "";
				document.querySelectorAll("img, svg, picture, video").forEach((n) => n.remove());
				const meta = document.createElement("meta");
				meta.setAttribute("charset", "utf-8");
				document.head.appendChild(meta);
				const title = document.createElement("title");
				title.textContent = ${JSON.stringify(rendered.title)};
				document.head.appendChild(title);
				const style = document.createElement("style");
				style.textContent = ${JSON.stringify(rendered.css)};
				document.head.appendChild(style);
				document.body.innerHTML = ${JSON.stringify(
      `<div class="markdown-preview-view markdown-rendered">${rendered.bodyHtml}</div>`
    )};
				document.documentElement.style.background = "#fff";
				document.body.style.background = "#fff";
				document.body.style.margin = "0";
			})();
		`);
    await webview.executeJavaScript(`
			Promise.all(
				Array.from(document.images).map((img) => {
					if (img.complete) return Promise.resolve();
					return new Promise((resolve) => {
						img.onload = img.onerror = () => resolve();
						setTimeout(resolve, 3000);
					});
				}),
			);
		`);
    await sleep2(250);
    const hf = headerFooterTemplates(profile);
    const page = profile.page;
    let pageSize = page.pageSize;
    if (page.pageSize === "Custom") {
      pageSize = {
        width: page.pageWidthMm / 25.4,
        height: page.pageHeightMm / 25.4
      };
    }
    const printOptions = {
      landscape: false,
      printBackground: page.printBackground,
      pageSize,
      scale: 1,
      margins: {
        marginType: "custom",
        top: page.marginTopMm / 25.4,
        bottom: page.marginBottomMm / 25.4,
        left: page.marginLeftMm / 25.4,
        right: page.marginRightMm / 25.4
      },
      displayHeaderFooter: hf.displayHeaderFooter,
      headerTemplate: hf.headerTemplate,
      footerTemplate: hf.footerTemplate
    };
    const data = await webview.printToPDF(printOptions);
    return data;
  } finally {
    webview.remove();
  }
}
function createHiddenWebview() {
  const webview = createEl("webview", {
    cls: "beautiful-pdf-print-webview",
    attr: {
      webpreferences: "nodeIntegration=yes"
    }
  });
  webview.src = "app://obsidian.md/help.html";
  return webview;
}
function waitForDomReady(webview) {
  return new Promise((resolve, reject) => {
    const t = window.setTimeout(() => reject(new Error("webview timeout")), 15e3);
    webview.addEventListener(
      "dom-ready",
      () => {
        window.clearTimeout(t);
        resolve();
      },
      { once: true }
    );
  });
}
function sleep2(ms) {
  return new Promise((r) => window.setTimeout(r, ms));
}

// src/preview.ts
var import_obsidian3 = require("obsidian");

// src/profiles.ts
var KOR = '"KoPubWorldDotum", "KoPub Dotum", "Apple SD Gothic Neo", "NanumGothic", "Malgun Gothic", sans-serif';
var KOR_SERIF = '"KoPubWorldBatang", "Apple Myungjo", "NanumMyeongjo", "Batang", serif';
var MONO = '"Menlo", "Consolas", "D2Coding", monospace';
function el(partial) {
  return {
    fontFamily: KOR,
    fontWeight: "normal",
    align: "left",
    color: "#1a1a1a",
    marginTop: 0,
    marginBottom: 8,
    ...partial
  };
}
function baseElements() {
  return {
    h1: el({
      fontSize: 22,
      fontWeight: "bold",
      align: "center",
      marginTop: 0,
      marginBottom: 16,
      lineHeight: 130
    }),
    h2: el({
      fontSize: 18,
      fontWeight: "bold",
      marginTop: 18,
      marginBottom: 10,
      lineHeight: 135
    }),
    h3: el({
      fontSize: 15,
      fontWeight: "bold",
      marginTop: 14,
      marginBottom: 8,
      lineHeight: 135
    }),
    h4: el({
      fontSize: 13,
      fontWeight: "bold",
      marginTop: 12,
      marginBottom: 6
    }),
    h5: el({
      fontSize: 12,
      fontWeight: "bold",
      marginTop: 10,
      marginBottom: 4
    }),
    h6: el({
      fontSize: 11,
      fontWeight: "bold",
      marginTop: 8,
      marginBottom: 4,
      color: "#444444"
    }),
    body: el({
      fontSize: 11,
      lineHeight: 170,
      marginBottom: 8
    }),
    blockquote: el({
      fontSize: 11,
      color: "#444444",
      paddingLeft: 12,
      marginTop: 8,
      marginBottom: 8,
      lineHeight: 160,
      backgroundColor: "#f7f7f7",
      framePreset: "accent-bar"
    }),
    list: el({
      fontSize: 11,
      marginBottom: 6,
      lineHeight: 160,
      paddingLeft: 4
    }),
    taskList: el({
      fontSize: 11,
      marginBottom: 4,
      lineHeight: 155
    }),
    codeInline: el({
      fontFamily: MONO,
      fontSize: 10,
      color: "#b00020",
      marginBottom: 0,
      backgroundColor: "#f0f0f0"
    }),
    codeBlock: el({
      fontFamily: MONO,
      fontSize: 9.5,
      marginTop: 8,
      marginBottom: 10,
      lineHeight: 145,
      paddingLeft: 0,
      backgroundColor: "#f4f4f4"
    }),
    hr: el({
      fontSize: 11,
      marginTop: 16,
      marginBottom: 16,
      color: "#cccccc"
    }),
    table: el({
      fontSize: 10,
      marginTop: 8,
      marginBottom: 10,
      lineHeight: 140
    }),
    tableHeader: el({
      fontSize: 10,
      fontWeight: "bold",
      marginBottom: 0,
      backgroundColor: "#f0f0f0"
    }),
    callout: el({
      fontSize: 11,
      marginTop: 10,
      marginBottom: 10,
      paddingLeft: 8,
      lineHeight: 155,
      backgroundColor: "#f5f8fb",
      framePreset: "accent-bar"
    }),
    calloutTitle: el({
      fontSize: 11,
      fontWeight: "bold",
      marginBottom: 4
    }),
    image: el({
      fontSize: 11,
      align: "center",
      marginTop: 10,
      marginBottom: 10
    }),
    link: el({
      fontSize: 11,
      color: "#0b57d0",
      marginBottom: 0
    }),
    footnote: el({
      fontSize: 9,
      color: "#555555",
      marginTop: 12,
      lineHeight: 140
    }),
    embed: el({
      fontSize: 10,
      marginTop: 8,
      marginBottom: 8,
      paddingLeft: 8,
      lineHeight: 150,
      color: "#333333",
      backgroundColor: "#fafafa",
      framePreset: "accent-bar"
    })
  };
}
function basePage(overrides = {}) {
  return {
    pageSize: "A4",
    pageWidthMm: 210,
    pageHeightMm: 297,
    marginTopMm: 20,
    marginBottomMm: 20,
    marginLeftMm: 18,
    marginRightMm: 18,
    lineHeight: 170,
    pageNumber: "bottom-center",
    pageNumberFormat: "{page}",
    useFilenameAsTitle: true,
    headerText: "",
    headerAlign: "left",
    footerText: "",
    footerAlign: "center",
    printBackground: true,
    ...overrides
  };
}
function cloneElements(src) {
  const out = {};
  for (const key of Object.keys(src)) {
    out[key] = { ...src[key] };
  }
  return out;
}
function createReportProfile() {
  const elements = baseElements();
  elements.h1.fontFamily = KOR;
  elements.h1.fontSize = 22;
  elements.h1.align = "center";
  elements.h1.color = "#111827";
  elements.h1.marginBottom = 20;
  elements.h2.fontSize = 15;
  elements.h2.color = "#1e3a5f";
  elements.h2.marginTop = 22;
  elements.h3.fontSize = 12.5;
  elements.h3.color = "#1e3a5f";
  elements.body.fontSize = 10.5;
  elements.body.lineHeight = 165;
  elements.body.color = "#1f2937";
  elements.blockquote.color = "#374151";
  elements.blockquote.backgroundColor = "#eef2f7";
  elements.blockquote.framePreset = "accent-bar";
  elements.codeInline.color = "#9f1239";
  elements.codeInline.backgroundColor = "#fce7f3";
  elements.codeBlock.backgroundColor = "#f3f4f6";
  elements.tableHeader.backgroundColor = "#1e3a5f";
  elements.tableHeader.color = "#ffffff";
  elements.callout.backgroundColor = "#eef2f7";
  elements.callout.framePreset = "accent-bar";
  elements.link.color = "#1d4ed8";
  elements.embed.backgroundColor = "#f8fafc";
  elements.embed.framePreset = "accent-bar";
  return {
    id: "report",
    name: "Report",
    page: basePage({
      marginTopMm: 28,
      marginBottomMm: 24,
      marginLeftMm: 24,
      marginRightMm: 24,
      lineHeight: 165,
      pageNumber: "bottom-center",
      pageNumberFormat: "- {page} -",
      useFilenameAsTitle: true,
      headerText: "",
      footerText: ""
    }),
    elements
  };
}
function createLifeProfile() {
  const elements = baseElements();
  elements.h1.align = "left";
  elements.h1.fontSize = 26;
  elements.h1.fontWeight = "700";
  elements.h1.color = "#292524";
  elements.h1.marginBottom = 10;
  elements.h2.fontSize = 17;
  elements.h2.color = "#78716c";
  elements.h2.fontWeight = "600";
  elements.h2.marginTop = 14;
  elements.h3.fontSize = 14;
  elements.h3.color = "#a8a29e";
  elements.body.fontSize = 13;
  elements.body.lineHeight = 200;
  elements.body.color = "#44403c";
  elements.blockquote.color = "#78716c";
  elements.blockquote.backgroundColor = "#faf5f0";
  elements.blockquote.framePreset = "soft-fill";
  elements.list.fontSize = 13;
  elements.list.lineHeight = 190;
  elements.taskList.fontSize = 13;
  elements.codeInline.color = "#b45309";
  elements.codeInline.backgroundColor = "#fff7ed";
  elements.codeBlock.backgroundColor = "#f5f5f4";
  elements.codeBlock.fontSize = 11;
  elements.tableHeader.backgroundColor = "#d6d3d1";
  elements.tableHeader.color = "#1c1917";
  elements.callout.backgroundColor = "#fffbeb";
  elements.callout.framePreset = "soft-fill";
  elements.link.color = "#c2410c";
  elements.hr.color = "#e7e5e4";
  elements.embed.backgroundColor = "#fafaf9";
  elements.embed.framePreset = "soft-fill";
  return {
    id: "life",
    name: "Everyday",
    page: basePage({
      marginTopMm: 14,
      marginBottomMm: 14,
      marginLeftMm: 14,
      marginRightMm: 14,
      lineHeight: 200,
      pageNumber: "bottom-right",
      pageNumberFormat: "{page}",
      useFilenameAsTitle: true,
      headerText: "",
      footerAlign: "right"
    }),
    elements
  };
}
function createPlanProfile() {
  const elements = baseElements();
  elements.h1.fontFamily = KOR_SERIF;
  elements.h1.fontSize = 24;
  elements.h1.align = "center";
  elements.h1.color = "#0f172a";
  elements.h1.marginBottom = 8;
  elements.h2.fontFamily = KOR_SERIF;
  elements.h2.fontSize = 14;
  elements.h2.align = "left";
  elements.h2.color = "#0369a1";
  elements.h2.marginTop = 16;
  elements.h2.marginBottom = 6;
  elements.h3.fontSize = 11.5;
  elements.h3.color = "#0284c7";
  elements.body.fontSize = 9.5;
  elements.body.lineHeight = 150;
  elements.body.color = "#334155";
  elements.blockquote.fontSize = 9.5;
  elements.blockquote.color = "#0369a1";
  elements.blockquote.backgroundColor = "#e0f2fe";
  elements.blockquote.framePreset = "outline-card";
  elements.list.fontSize = 9.5;
  elements.list.lineHeight = 145;
  elements.codeInline.color = "#0e7490";
  elements.codeInline.backgroundColor = "#ecfeff";
  elements.codeBlock.backgroundColor = "#0f172a";
  elements.codeBlock.color = "#e2e8f0";
  elements.codeBlock.fontSize = 8.5;
  elements.table.fontSize = 9;
  elements.tableHeader.fontSize = 9;
  elements.tableHeader.backgroundColor = "#0369a1";
  elements.tableHeader.color = "#ffffff";
  elements.callout.backgroundColor = "#f0f9ff";
  elements.callout.fontSize = 9.5;
  elements.callout.framePreset = "outline-card";
  elements.link.color = "#0284c7";
  elements.hr.color = "#bae6fd";
  elements.embed.backgroundColor = "#f8fafc";
  elements.embed.framePreset = "outline-card";
  elements.footnote.fontSize = 8;
  return {
    id: "plan",
    name: "Proposal",
    page: basePage({
      marginTopMm: 18,
      marginBottomMm: 16,
      marginLeftMm: 16,
      marginRightMm: 16,
      lineHeight: 150,
      pageNumber: "top-center",
      pageNumberFormat: "{page} / {pages}",
      useFilenameAsTitle: true,
      headerText: "Proposal",
      headerAlign: "right",
      footerText: ""
    }),
    elements
  };
}
function createSampleProfiles() {
  return [createReportProfile(), createLifeProfile(), createPlanProfile()];
}
function createDefaultSettings() {
  const profiles = createSampleProfiles();
  return {
    settingsVersion: 3,
    activeProfileId: profiles[0].id,
    profiles
  };
}
function getActiveProfile(settings) {
  var _a;
  return (_a = settings.profiles.find((p) => p.id === settings.activeProfileId)) != null ? _a : settings.profiles[0];
}
function cloneProfile(profile, newName) {
  return {
    id: `profile-${Date.now()}`,
    name: newName,
    page: { ...profile.page },
    elements: cloneElements(profile.elements)
  };
}
function createBlankProfile(name) {
  const base = createReportProfile();
  return {
    id: `profile-${Date.now()}`,
    name,
    page: { ...base.page },
    elements: cloneElements(base.elements)
  };
}

// src/preview.ts
var PreviewModal = class extends import_obsidian3.Modal {
  constructor(app, plugin, file) {
    super(app);
    this.iframeEl = null;
    this.statusEl = null;
    this.blobUrl = null;
    this.generating = false;
    this.plugin = plugin;
    this.file = file;
  }
  onOpen() {
    const { contentEl } = this;
    this.modalEl.addClass("beautiful-pdf-preview-modal");
    contentEl.empty();
    contentEl.createEl("h2", { text: "Beautiful PDF preview" });
    const toolbar = contentEl.createDiv({ cls: "beautiful-pdf-toolbar" });
    const select = toolbar.createEl("select");
    for (const p of this.plugin.settings.profiles) {
      const opt = select.createEl("option", { text: p.name, value: p.id });
      if (p.id === this.plugin.settings.activeProfileId)
        opt.selected = true;
    }
    select.onchange = async () => {
      this.plugin.settings.activeProfileId = select.value;
      await this.plugin.saveSettings();
      await this.refresh();
    };
    const refreshBtn = toolbar.createEl("button", { text: "Refresh" });
    refreshBtn.onclick = () => void this.refresh();
    const saveBtn = toolbar.createEl("button", {
      text: "Save PDF",
      cls: "mod-cta"
    });
    saveBtn.onclick = async () => {
      const profile = getActiveProfile(this.plugin.settings);
      await exportPdfToFile(this.app, this.file, profile);
    };
    this.statusEl = toolbar.createDiv({ cls: "beautiful-pdf-status", text: "" });
    const wrap = contentEl.createDiv({ cls: "beautiful-pdf-frame-wrap" });
    this.iframeEl = wrap.createEl("iframe", {
      attr: { title: "PDF preview" }
    });
    void this.refresh();
  }
  async refresh() {
    if (this.generating)
      return;
    this.generating = true;
    this.setStatus("Generating PDF\u2026");
    try {
      const profile = getActiveProfile(this.plugin.settings);
      const { data } = await generatePdf(this.app, this.file, profile);
      this.showPdf(data);
      this.setStatus(`Profile: ${profile.name}`);
    } catch (err) {
      console.error(err);
      this.setStatus("Failed");
      new import_obsidian3.Notice(`Preview failed: ${String(err)}`);
    } finally {
      this.generating = false;
    }
  }
  showPdf(data) {
    if (this.blobUrl)
      URL.revokeObjectURL(this.blobUrl);
    const blob = new Blob([data], { type: "application/pdf" });
    this.blobUrl = URL.createObjectURL(blob);
    if (this.iframeEl) {
      this.iframeEl.src = this.blobUrl;
    }
  }
  setStatus(text) {
    if (this.statusEl)
      this.statusEl.setText(text);
  }
  onClose() {
    if (this.blobUrl)
      URL.revokeObjectURL(this.blobUrl);
    this.contentEl.empty();
  }
};
var ProfileSuggestModal = class extends import_obsidian3.Modal {
  constructor(app, plugin, file, onChoose) {
    super(app);
    this.plugin = plugin;
    this.file = file;
    this.onChoose = onChoose;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Choose profile" });
    for (const profile of this.plugin.settings.profiles) {
      new import_obsidian3.Setting(contentEl).setName(profile.name).addButton(
        (btn) => btn.setButtonText("Select").setCta().onClick(() => {
          this.close();
          this.onChoose(profile);
        })
      );
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/settings.ts
var import_obsidian4 = require("obsidian");

// src/types.ts
var FRAME_PRESET_OPTIONS = [
  { id: "accent-bar", label: "Accent bar (left edge)" },
  { id: "outline-card", label: "Outline card" },
  { id: "soft-fill", label: "Soft fill (no border)" }
];
var ELEMENTS_WITH_FRAME = [
  "blockquote",
  "callout",
  "embed"
];
var ELEMENT_LABELS = {
  h1: "Heading # (H1)",
  h2: "Heading ## (H2)",
  h3: "Heading ### (H3)",
  h4: "Heading #### (H4)",
  h5: "Heading ##### (H5)",
  h6: "Heading ###### (H6)",
  body: "Body",
  blockquote: "Blockquote",
  list: "List",
  taskList: "Task list",
  codeInline: "Inline code",
  codeBlock: "Code block",
  hr: "Horizontal rule",
  table: "Table body",
  tableHeader: "Table header",
  callout: "Callout",
  calloutTitle: "Callout title",
  image: "Image",
  link: "Link",
  footnote: "Footnote",
  embed: "Embed"
};
var ELEMENT_KEYS = Object.keys(ELEMENT_LABELS);
var ELEMENT_GROUPS = [
  { id: "headings", label: "Headings", keys: ["h1", "h2", "h3", "h4", "h5", "h6"] },
  { id: "body", label: "Body \xB7 quote", keys: ["body", "blockquote"] },
  { id: "lists", label: "Lists", keys: ["list", "taskList"] },
  { id: "code", label: "Code", keys: ["codeInline", "codeBlock"] },
  { id: "table", label: "Tables", keys: ["table", "tableHeader"] },
  { id: "callout", label: "Callouts", keys: ["callout", "calloutTitle"] },
  { id: "misc", label: "Other", keys: ["hr", "image", "link", "footnote", "embed"] }
];
var ELEMENT_PREVIEW_TEXT = {
  h1: "Heading sample (#)",
  h2: "Heading sample (##)",
  h3: "Heading sample (###)",
  h4: "Heading sample (####)",
  h5: "Heading sample (#####)",
  h6: "Heading sample (######)",
  body: "Body text looks like this. Check line height and font size.",
  blockquote: "A blockquote sample. Check the left border and colors.",
  list: "\u2022 List item sample",
  taskList: "\u2611 Task list item sample",
  codeInline: "const x = 1",
  codeBlock: "function hello() {\n  return true;\n}",
  hr: "\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
  table: "Table cell sample",
  tableHeader: "Table header sample",
  callout: "Callout body sample.",
  calloutTitle: "Callout title",
  image: "[ Image align \xB7 spacing ]",
  link: "Link text sample",
  footnote: "Footnote sample\xB9",
  embed: "Embed preview area"
};
var ELEMENTS_WITH_BACKGROUND = [
  "blockquote",
  "codeInline",
  "codeBlock",
  "tableHeader",
  "callout",
  "embed"
];
var SETTINGS_VERSION = 3;

// src/settings.ts
var BeautifulPdfSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.ui = {
      pageOpen: false,
      marginsOpen: false,
      pageNumberOpen: false,
      headerFooterOpen: false,
      morePageOpen: false,
      groupOpen: {},
      elementOpen: {}
    };
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("beautiful-pdf-settings");
    this.renderProfiles(containerEl);
    this.renderPageSection(containerEl);
    this.renderElementsSection(containerEl);
    const tip = containerEl.createDiv({ cls: "beautiful-pdf-tip" });
    tip.createEl("strong", { text: "Page break: " });
    tip.appendText("Insert ");
    tip.createEl("code", { text: "%%pdf-pagebreak%%" });
    tip.appendText(" in a note, or use the command ");
    tip.createEl("code", { text: "Insert page break" });
    tip.appendText(".");
  }
  /* ---------- Profiles ---------- */
  renderProfiles(containerEl) {
    const section = containerEl.createDiv({ cls: "beautiful-pdf-section" });
    new import_obsidian4.Setting(section).setName("Document profiles").setHeading();
    const chips = section.createDiv({ cls: "beautiful-pdf-profile-chips" });
    for (const p of this.plugin.settings.profiles) {
      const chip = chips.createEl("button", {
        cls: "beautiful-pdf-profile-chip" + (p.id === this.plugin.settings.activeProfileId ? " is-active" : ""),
        text: p.name,
        attr: { type: "button" }
      });
      chip.onclick = () => {
        void (async () => {
          this.plugin.settings.activeProfileId = p.id;
          await this.plugin.saveSettings();
          this.display();
        })();
      };
    }
    const actions = section.createDiv({ cls: "beautiful-pdf-profile-actions" });
    const mkAction = (label, cls, fn) => {
      const b = actions.createEl("button", {
        text: label,
        cls: `beautiful-pdf-action-btn ${cls}`,
        attr: { type: "button" }
      });
      b.onclick = () => {
        void fn();
      };
    };
    mkAction("New profile", "", async () => {
      const profile2 = createBlankProfile(
        `Profile ${this.plugin.settings.profiles.length + 1}`
      );
      this.plugin.settings.profiles.push(profile2);
      this.plugin.settings.activeProfileId = profile2.id;
      await this.plugin.saveSettings();
      this.display();
    });
    mkAction("Duplicate", "", async () => {
      const active = getActiveProfile(this.plugin.settings);
      const copy = cloneProfile(active, `${active.name} copy`);
      this.plugin.settings.profiles.push(copy);
      this.plugin.settings.activeProfileId = copy.id;
      await this.plugin.saveSettings();
      this.display();
    });
    mkAction("Delete", "is-danger", async () => {
      if (this.plugin.settings.profiles.length <= 1)
        return;
      const id = this.plugin.settings.activeProfileId;
      this.plugin.settings.profiles = this.plugin.settings.profiles.filter(
        (p) => p.id !== id
      );
      this.plugin.settings.activeProfileId = this.plugin.settings.profiles[0].id;
      await this.plugin.saveSettings();
      this.display();
    });
    section.createEl("hr", { cls: "beautiful-pdf-divider" });
    const profile = getActiveProfile(this.plugin.settings);
    new import_obsidian4.Setting(section).setName("Profile name").addText(
      (text) => text.setValue(profile.name).onChange((v) => {
        void (async () => {
          profile.name = v.trim() || profile.name;
          await this.plugin.saveSettings();
          const active = chips.querySelector(".is-active");
          if (active)
            active.setText(profile.name);
        })();
      })
    );
  }
  /* ---------- Page ---------- */
  renderPageSection(containerEl) {
    const page = getActiveProfile(this.plugin.settings).page;
    page.lineHeight = toLineHeightPercent(page.lineHeight);
    const summary = `${page.pageSize} \xB7 margins ${page.marginTopMm}/${page.marginBottomMm}/${page.marginLeftMm}/${page.marginRightMm}mm`;
    this.collapsible(
      containerEl,
      "Page",
      summary,
      this.ui.pageOpen,
      (open) => {
        this.ui.pageOpen = open;
      },
      (body) => {
        var _a;
        const titleToggle = this.rowBox(body);
        new import_obsidian4.Setting(titleToggle).setName("Use filename as title").addToggle(
          (tg) => tg.setValue(page.useFilenameAsTitle).onChange((v) => {
            void (async () => {
              page.useFilenameAsTitle = v;
              await this.plugin.saveSettings();
            })();
          })
        );
        const sizeBox = this.rowBox(body);
        new import_obsidian4.Setting(sizeBox).setName("Page size").addDropdown((dd) => {
          ["A4", "Letter", "Legal", "Custom"].forEach(
            (s) => dd.addOption(s, s)
          );
          dd.setValue(page.pageSize).onChange((v) => {
            void (async () => {
              page.pageSize = v;
              await this.plugin.saveSettings();
              this.display();
            })();
          });
        });
        if (page.pageSize === "Custom") {
          const customBox = this.rowBox(body);
          this.numSetting(customBox, "Width (mm)", page.pageWidthMm, async (n) => {
            page.pageWidthMm = n;
          });
          this.numSetting(customBox, "Height (mm)", page.pageHeightMm, async (n) => {
            page.pageHeightMm = n;
          });
        }
        this.collapsible(
          body,
          "Margins",
          `${page.marginTopMm} / ${page.marginBottomMm} / ${page.marginLeftMm} / ${page.marginRightMm} mm`,
          this.ui.marginsOpen,
          (o) => {
            this.ui.marginsOpen = o;
          },
          (inner) => {
            this.numSetting(inner, "Top (mm)", page.marginTopMm, async (n) => {
              page.marginTopMm = n;
            });
            this.numSetting(inner, "Bottom (mm)", page.marginBottomMm, async (n) => {
              page.marginBottomMm = n;
            });
            this.numSetting(inner, "Left (mm)", page.marginLeftMm, async (n) => {
              page.marginLeftMm = n;
            });
            this.numSetting(inner, "Right (mm)", page.marginRightMm, async (n) => {
              page.marginRightMm = n;
            });
          },
          true
        );
        const pnLabel = (_a = {
          none: "None",
          "bottom-center": "Bottom center",
          "bottom-right": "Bottom right",
          "top-center": "Top center"
        }[page.pageNumber]) != null ? _a : page.pageNumber;
        this.collapsible(
          body,
          "Page numbers",
          pnLabel,
          this.ui.pageNumberOpen,
          (o) => {
            this.ui.pageNumberOpen = o;
          },
          (inner) => {
            new import_obsidian4.Setting(inner).setName("Position").addDropdown((dd) => {
              const opts = {
                none: "None",
                "bottom-center": "Bottom center",
                "bottom-right": "Bottom right",
                "top-center": "Top center"
              };
              Object.keys(opts).forEach((k) => {
                dd.addOption(k, opts[k]);
              });
              dd.setValue(page.pageNumber).onChange((v) => {
                void (async () => {
                  page.pageNumber = v;
                  await this.plugin.saveSettings();
                  this.display();
                })();
              });
            });
            new import_obsidian4.Setting(inner).setName("Format").addText(
              (t) => t.setPlaceholder("{page} / {pages}").setValue(page.pageNumberFormat).onChange((v) => {
                void (async () => {
                  page.pageNumberFormat = v;
                  await this.plugin.saveSettings();
                })();
              })
            );
          },
          true
        );
        const hfSummary = [
          page.headerText ? `Header (${page.headerAlign})` : null,
          page.footerText ? `Footer (${page.footerAlign})` : null
        ].filter(Boolean).join(" \xB7 ") || "None";
        this.collapsible(
          body,
          "Header \xB7 footer",
          hfSummary,
          this.ui.headerFooterOpen,
          (o) => {
            this.ui.headerFooterOpen = o;
          },
          (inner) => {
            new import_obsidian4.Setting(inner).setName("Header text").addText(
              (t) => t.setValue(page.headerText).onChange((v) => {
                void (async () => {
                  page.headerText = v;
                  await this.plugin.saveSettings();
                })();
              })
            );
            new import_obsidian4.Setting(inner).setName("Header align").addDropdown((dd) => {
              var _a2;
              this.addHfAlignOptions(dd);
              dd.setValue((_a2 = page.headerAlign) != null ? _a2 : "left").onChange((v) => {
                void (async () => {
                  page.headerAlign = v;
                  await this.plugin.saveSettings();
                })();
              });
            });
            new import_obsidian4.Setting(inner).setName("Footer text").addText(
              (t) => t.setValue(page.footerText).onChange((v) => {
                void (async () => {
                  page.footerText = v;
                  await this.plugin.saveSettings();
                })();
              })
            );
            new import_obsidian4.Setting(inner).setName("Footer align").addDropdown((dd) => {
              var _a2;
              this.addHfAlignOptions(dd);
              dd.setValue((_a2 = page.footerAlign) != null ? _a2 : "center").onChange((v) => {
                void (async () => {
                  page.footerAlign = v;
                  await this.plugin.saveSettings();
                })();
              });
            });
          },
          true
        );
        this.collapsible(
          body,
          "More",
          `Line height ${page.lineHeight}% \xB7 background ${page.printBackground ? "on" : "off"}`,
          this.ui.morePageOpen,
          (o) => {
            this.ui.morePageOpen = o;
          },
          (inner) => {
            new import_obsidian4.Setting(inner).setName("Default line height (%)").addText(
              (t) => t.setValue(String(page.lineHeight)).onChange((v) => {
                void (async () => {
                  const n = parseFloat(v);
                  if (!Number.isNaN(n) && n > 0) {
                    page.lineHeight = toLineHeightPercent(n);
                    await this.plugin.saveSettings();
                  }
                })();
              })
            );
            new import_obsidian4.Setting(inner).setName("Print background").addToggle(
              (tg) => tg.setValue(page.printBackground).onChange((v) => {
                void (async () => {
                  page.printBackground = v;
                  await this.plugin.saveSettings();
                })();
              })
            );
          },
          true
        );
      }
    );
  }
  addHfAlignOptions(dd) {
    dd.addOption("left", "Left");
    dd.addOption("center", "Center");
    dd.addOption("right", "Right");
  }
  /* ---------- Markdown elements ---------- */
  renderElementsSection(containerEl) {
    var _a;
    const section = containerEl.createDiv({ cls: "beautiful-pdf-section" });
    new import_obsidian4.Setting(section).setName("Markdown elements").setHeading();
    const elements = getActiveProfile(this.plugin.settings).elements;
    for (const group of ELEMENT_GROUPS) {
      const open = (_a = this.ui.groupOpen[group.id]) != null ? _a : false;
      this.collapsible(
        section,
        group.label,
        `${group.keys.length} elements`,
        open,
        (o) => {
          this.ui.groupOpen[group.id] = o;
        },
        (body) => {
          for (const key of group.keys) {
            this.renderElementRow(body, key, elements[key]);
          }
        }
      );
    }
  }
  renderElementRow(parent, key, style) {
    var _a;
    if (style.lineHeight != null) {
      style.lineHeight = toLineHeightPercent(style.lineHeight);
    }
    const expanded = !!this.ui.elementOpen[key];
    const row = parent.createDiv({
      cls: "beautiful-pdf-el-row" + (expanded ? " is-open" : "")
    });
    const head = row.createDiv({ cls: "beautiful-pdf-el-head" });
    head.createDiv({ cls: "beautiful-pdf-el-label", text: ELEMENT_LABELS[key] });
    const preview = head.createDiv({ cls: "beautiful-pdf-el-preview" });
    this.paintPreview(preview, key, style);
    head.createSpan({
      cls: "beautiful-pdf-el-chevron",
      text: expanded ? "\u25BE" : "\u25B8"
    });
    head.onclick = () => {
      this.ui.elementOpen[key] = !expanded;
      this.display();
    };
    if (!expanded)
      return;
    const editors = row.createDiv({ cls: "beautiful-pdf-el-editors" });
    const refreshPreview = () => this.paintPreview(preview, key, style);
    if (ELEMENTS_WITH_FRAME.includes(key)) {
      new import_obsidian4.Setting(editors).setName("Box style").addDropdown((dd) => {
        var _a2;
        for (const opt of FRAME_PRESET_OPTIONS) {
          dd.addOption(opt.id, opt.label);
        }
        dd.setValue((_a2 = style.framePreset) != null ? _a2 : "accent-bar").onChange((v) => {
          void (async () => {
            style.framePreset = v;
            await this.plugin.saveSettings();
            refreshPreview();
          })();
        });
      });
    }
    new import_obsidian4.Setting(editors).setName("Font").addText(
      (t) => t.setValue(style.fontFamily).onChange((v) => {
        void (async () => {
          style.fontFamily = v;
          await this.plugin.saveSettings();
          refreshPreview();
        })();
      })
    );
    new import_obsidian4.Setting(editors).setName("Size (pt)").addText(
      (t) => t.setValue(String(style.fontSize)).onChange((v) => {
        void (async () => {
          const n = parseFloat(v);
          if (!Number.isNaN(n)) {
            style.fontSize = n;
            await this.plugin.saveSettings();
            refreshPreview();
          }
        })();
      })
    );
    new import_obsidian4.Setting(editors).setName("Weight").addDropdown((dd) => {
      ["normal", "bold", "300", "500", "600", "700"].forEach(
        (w) => {
          dd.addOption(w, w);
        }
      );
      dd.setValue(style.fontWeight).onChange((v) => {
        void (async () => {
          style.fontWeight = v;
          await this.plugin.saveSettings();
          refreshPreview();
        })();
      });
    });
    new import_obsidian4.Setting(editors).setName("Align").addDropdown((dd) => {
      ["left", "center", "right", "justify"].forEach((a) => {
        dd.addOption(a, a);
      });
      dd.setValue(style.align).onChange((v) => {
        void (async () => {
          style.align = v;
          await this.plugin.saveSettings();
          refreshPreview();
        })();
      });
    });
    this.addColorSetting(editors, "Text color", style.color, async (v) => {
      style.color = v;
      await this.plugin.saveSettings();
      refreshPreview();
    });
    if (ELEMENTS_WITH_BACKGROUND.includes(key)) {
      this.addColorSetting(
        editors,
        "Background",
        (_a = style.backgroundColor) != null ? _a : "#ffffff",
        async (v) => {
          style.backgroundColor = v;
          await this.plugin.saveSettings();
          refreshPreview();
        }
      );
    }
    new import_obsidian4.Setting(editors).setName("Margin top (pt)").addText(
      (t) => t.setValue(String(style.marginTop)).onChange((v) => {
        void (async () => {
          const n = parseFloat(v);
          if (!Number.isNaN(n)) {
            style.marginTop = n;
            await this.plugin.saveSettings();
            refreshPreview();
          }
        })();
      })
    );
    new import_obsidian4.Setting(editors).setName("Margin bottom (pt)").addText(
      (t) => t.setValue(String(style.marginBottom)).onChange((v) => {
        void (async () => {
          const n = parseFloat(v);
          if (!Number.isNaN(n)) {
            style.marginBottom = n;
            await this.plugin.saveSettings();
            refreshPreview();
          }
        })();
      })
    );
    if (style.lineHeight != null) {
      new import_obsidian4.Setting(editors).setName("Line height (%)").addText(
        (t) => t.setValue(String(style.lineHeight)).onChange((v) => {
          void (async () => {
            const n = parseFloat(v);
            if (!Number.isNaN(n) && n > 0) {
              style.lineHeight = toLineHeightPercent(n);
              await this.plugin.saveSettings();
              refreshPreview();
            }
          })();
        })
      );
    }
  }
  addColorSetting(parent, name, value, onChange) {
    var _a;
    const setting = new import_obsidian4.Setting(parent).setName(name);
    let textComp = null;
    const initial = (_a = normalizeHex(value)) != null ? _a : "#1a1a1a";
    setting.addText((t) => {
      textComp = t;
      t.inputEl.addClass("beautiful-pdf-hex-input");
      t.setPlaceholder("#1a1a1a");
      t.setValue(value).onChange((v) => {
        void (async () => {
          await onChange(v);
          const hex = normalizeHex(v);
          if (hex && colorInput)
            colorInput.value = hex;
          refreshSwatch();
        })();
      });
    });
    const colorInput = setting.controlEl.createEl("input", {
      cls: "beautiful-pdf-color-picker",
      attr: { type: "color", value: initial, title: "Pick color" }
    });
    colorInput.addEventListener("input", () => {
      void (async () => {
        const v = colorInput.value;
        textComp == null ? void 0 : textComp.setValue(v);
        await onChange(v);
        refreshSwatch();
      })();
    });
    const refreshSwatch = () => {
    };
  }
  paintPreview(el2, key, style) {
    var _a, _b;
    el2.empty();
    el2.addClass(`beautiful-pdf-preview-kind-${key}`);
    const sample = el2.createDiv({ cls: "beautiful-pdf-preview-sample" });
    sample.setText(ELEMENT_PREVIEW_TEXT[key]);
    const dynamic = {
      fontFamily: style.fontFamily,
      fontSize: `${Math.min(style.fontSize, 22)}pt`,
      fontWeight: style.fontWeight,
      textAlign: style.align,
      color: style.color
    };
    if (style.lineHeight != null) {
      dynamic.lineHeight = lineHeightCss(style.lineHeight);
    }
    if (style.backgroundColor && ELEMENTS_WITH_BACKGROUND.includes(key)) {
      sample.addClass("has-bg");
      dynamic.background = style.backgroundColor;
    }
    if (key === "codeInline" || key === "codeBlock") {
      sample.addClass("is-code");
      dynamic.background = (_a = style.backgroundColor) != null ? _a : "rgba(0,0,0,0.06)";
      dynamic.fontFamily = style.fontFamily;
    }
    if (key === "hr") {
      sample.addClass("is-hr");
    }
    if (key === "link") {
      sample.addClass("is-link");
    }
    if (key === "table" || key === "tableHeader") {
      sample.addClass("is-table");
      if (key === "tableHeader") {
        sample.addClass("is-table-header");
        dynamic.background = (_b = style.backgroundColor) != null ? _b : "#f0f0f0";
      }
    }
    sample.setCssStyles(dynamic);
    if (key === "blockquote") {
      applyFramePreview(sample, "blockquote", style);
    }
    if (key === "callout") {
      applyFramePreview(sample, "callout", style);
    }
    if (key === "embed") {
      applyFramePreview(sample, "embed", style);
    }
  }
  collapsible(parent, title, summary, open, setOpen, renderBody, nested = false) {
    const box = parent.createDiv({
      cls: "beautiful-pdf-fold" + (nested ? " is-nested" : "") + (open ? " is-open" : "")
    });
    const head = box.createDiv({ cls: "beautiful-pdf-fold-head" });
    head.createSpan({ cls: "beautiful-pdf-fold-title", text: title });
    if (summary) {
      head.createSpan({ cls: "beautiful-pdf-fold-summary", text: summary });
    }
    head.createSpan({ cls: "beautiful-pdf-fold-chevron", text: open ? "\u25BE" : "\u25B8" });
    head.onclick = () => {
      setOpen(!open);
      this.display();
    };
    if (open) {
      const body = box.createDiv({ cls: "beautiful-pdf-fold-body" });
      renderBody(body);
    }
  }
  /** Same outer card chrome as nested folds, for single setting rows. */
  rowBox(parent) {
    return parent.createDiv({ cls: "beautiful-pdf-row-box" });
  }
  numSetting(containerEl, name, value, onChange) {
    new import_obsidian4.Setting(containerEl).setName(name).addText(
      (t) => t.setValue(String(value)).onChange((v) => {
        void (async () => {
          const n = parseFloat(v);
          if (!Number.isNaN(n)) {
            await onChange(n);
            await this.plugin.saveSettings();
          }
        })();
      })
    );
  }
};
function normalizeHex(value) {
  const v = value.trim();
  if (/^#[0-9a-fA-F]{6}$/.test(v))
    return v.toLowerCase();
  if (/^#[0-9a-fA-F]{3}$/.test(v)) {
    const r = v[1];
    const g = v[2];
    const b = v[3];
    return `#${r}${r}${g}${g}${b}${b}`.toLowerCase();
  }
  return null;
}

// src/main.ts
var BeautifulPdfPlugin = class extends import_obsidian5.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new BeautifulPdfSettingTab(this.app, this));
    this.addRibbonIcon("file-text", "Beautiful PDF preview", () => {
      void this.openPreview();
    });
    this.addCommand({
      id: "preview",
      name: "Preview current note as PDF",
      checkCallback: (checking) => {
        const file = this.getActiveMarkdownFile();
        if (!file)
          return false;
        if (!checking)
          void this.openPreview(file);
        return true;
      }
    });
    this.addCommand({
      id: "export",
      name: "Export current note to PDF",
      checkCallback: (checking) => {
        const file = this.getActiveMarkdownFile();
        if (!file)
          return false;
        if (!checking) {
          const profile = getActiveProfile(this.settings);
          void exportPdfToFile(this.app, file, profile);
        }
        return true;
      }
    });
    this.addCommand({
      id: "export-with-profile",
      name: "Export current note with profile\u2026",
      checkCallback: (checking) => {
        const file = this.getActiveMarkdownFile();
        if (!file)
          return false;
        if (!checking) {
          new ProfileSuggestModal(this.app, this, file, (profile) => {
            void exportPdfToFile(this.app, file, profile);
          }).open();
        }
        return true;
      }
    });
    this.addCommand({
      id: "insert-pagebreak",
      name: "Insert page break",
      editorCallback: (editor) => {
        const pos = editor.getCursor();
        const line = editor.getLine(pos.line);
        const needsLeadingNewline = pos.ch > 0 || line.length > 0 && pos.ch === line.length;
        const snippet = needsLeadingNewline ? `
${PAGE_BREAK_SNIPPET}` : PAGE_BREAK_SNIPPET;
        editor.replaceRange(snippet, pos);
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (!(file instanceof import_obsidian5.TFile) || file.extension !== "md")
          return;
        menu.addItem((item) => {
          item.setTitle("Beautiful PDF: Export").setIcon("file-text").onClick(() => {
            const profile = getActiveProfile(this.settings);
            void exportPdfToFile(this.app, file, profile);
          });
        });
        menu.addItem((item) => {
          item.setTitle("Beautiful PDF: Preview").setIcon("eye").onClick(() => {
            void this.openPreview(file);
          });
        });
      })
    );
  }
  async openPreview(file) {
    const target = file != null ? file : this.getActiveMarkdownFile();
    if (!target) {
      new import_obsidian5.Notice("Open a Markdown note first.");
      return;
    }
    new PreviewModal(this.app, this, target).open();
  }
  getActiveMarkdownFile() {
    var _a;
    const view = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
    return (_a = view == null ? void 0 : view.file) != null ? _a : null;
  }
  async loadSettings() {
    var _a, _b;
    const defaults = createDefaultSettings();
    const data = await this.loadData();
    if (!data || !Array.isArray(data.profiles) || data.profiles.length === 0) {
      this.settings = defaults;
      await this.saveSettings();
      return;
    }
    const sampleIds = /* @__PURE__ */ new Set(["report", "life", "plan"]);
    let profiles = data.profiles;
    const version = (_a = data.settingsVersion) != null ? _a : 1;
    if (version < SETTINGS_VERSION) {
      const custom = profiles.filter((p) => !sampleIds.has(p.id));
      profiles = [...createSampleProfiles(), ...custom];
    }
    const fallbackElements = defaults.profiles[0].elements;
    this.settings = {
      settingsVersion: SETTINGS_VERSION,
      activeProfileId: (_b = data.activeProfileId) != null ? _b : defaults.activeProfileId,
      profiles: profiles.map((p) => mergeProfile(p, fallbackElements))
    };
    if (!this.settings.profiles.some((p) => p.id === this.settings.activeProfileId)) {
      this.settings.activeProfileId = this.settings.profiles[0].id;
    }
    if (version < SETTINGS_VERSION) {
      await this.saveSettings();
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
function mergeProfile(raw, fallback) {
  var _a, _b;
  const elements = { ...fallback };
  for (const key of ELEMENT_KEYS) {
    if ((_a = raw.elements) == null ? void 0 : _a[key]) {
      const merged = { ...fallback[key], ...raw.elements[key] };
      if (merged.lineHeight != null) {
        merged.lineHeight = toLineHeightPercent(merged.lineHeight, (_b = fallback[key].lineHeight) != null ? _b : 170);
      }
      elements[key] = merged;
    }
  }
  const defaultPage = createDefaultSettings().profiles[0].page;
  const page = { ...defaultPage, ...raw.page };
  page.lineHeight = toLineHeightPercent(page.lineHeight, defaultPage.lineHeight);
  return {
    id: raw.id,
    name: raw.name,
    page,
    elements
  };
}
